version: '3.7'
services:
  spring-jpa-db:
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=spring-jpa-mapping
    volumes:
      - db:/var/lib/mysql
volumes:
  db: