server:
  port: 1234
spring:
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

rabbitmq:
  queue_en: q.en_translation_queue
  queue_jp: q.jp_translation_queue
  routing-key_en: en_private-routing-key
  routing-key_jp: jp_private-routing-key
  exchange: private_exchange_queue